package com.example.tourisme_medicale.models;

public enum Pays {
    ALBANIE, ALGÉRIE, ALLEMAGNE, ANDORRE, ANGOLA, ARGENTINE, ARMÉNIE, AUSTRALIE, AUTRICHE, AZERBAÏDJAN,
    BAHAMAS, BAHREÏN, BANGLADESH, BARBADE, BELARUS, BELGIQUE, BELIZE, BÉNIN, BHOUTAN, BOLIVIE,
    BOTSWANA, BRESIL, BRUNÉI, BULGARIE, BURUNDI, CAMBODGE, CAMEROUN, CANADA, CENTRAFRICAINE, CHILI,
    CHINE, CHYPRE, COLOMBIE, COMORES, CONGO,  CROATIE, CUBA, DANEMARK, DJIBOUTI, DOMINIQUE, ÉGYPTE, ÉQUATEUR,
    ÉRYTHRÉE, ESPAGNE, ESTONIE, ÉTHIOPIE, FIJI, FINLANDE, FRANCE, GABON, GAMBIE, GÉORGIE, GHANA, GRÈCE, GRENADE, GUATEMALA,
    GUINÉE,  GUYANA, HAÏTI, HONDURAS, HONGRIE, INDE, INDONÉSIE, IRAK, IRAN, IRLANDE, ISLANDE, ISRAËL, ITALIE, JAMAÏQUE, JAPON, JORDANIE, KAZAKHSTAN, KENYA, KIRGHIZISTAN, KIRIBATI, KOWEÏT, LAOS, LESOTHO, LETTONIE, LIBAN, LIBÉRIA, LIBYE, LIECHTENSTEIN, LITUANIE, LUXEMBOURG, MADAGASCAR, MALAISIE, MALAWI, MALDIVES, MALI, MALTE, MAROC, MARSHALL, MAURICE, MAURITANIE, MEXIQUE, MICRONÉSIE, MOLDAVIE, MONACO, MONGOLIE, MONTÉNÉGRO, MOZAMBIQUE, MYANMAR, NAMIBIE, NAURU, NÉPAL, NICARAGUA, NIGER, NIGÉRIA, NORVÈGE,  OMAN, OUGANDA, OUZBÉKISTAN, PAKISTAN, PALAOS, PALESTINE, PANAMA,PARAGUAY, PÉROU, PHILIPPINES, POLOGNE, PORTUGAL, QATAR, LEONE, SINGAPOUR, SLOVAQUIE, SLOVÉNIE, SOMALIE, SOUDAN,  SUEDE, SUISSE, SURINAME, SWAZILAND, SYRIE, TADJIKISTAN, TANZANIE, TCHAD, THAÏLANDE, TOGO, TONGA,  TUNISIE, TURKMÉNISTAN, TURQUIE, TUVALU, UKRAINE, URUGUAY, VANUATU, VATICAN, VENEZUELA, VIETNAM, YÉMEN, ZAMBIE, ZIMBABWE;
}
